<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus, Picture, Refresh } from '@element-plus/icons-vue'
import { api, jsonBody } from '../lib/api'

interface Binding { storageId:string; rootPath:string }
interface Album { id:string;name:string;description:string;coverMediaId?:string;backupMode:string;scanStatus:string;tags:string[];mediaCount:number;createdAt:string;primary?:Binding;backup?:Binding }
interface StorageConnection { id:string;name:string;type:string;status:string }
const albums=ref<Album[]>([]);const storages=ref<StorageConnection[]>([]);const loading=ref(false);const dialog=ref(false);const selectedTag=ref('')
const form=reactive({name:'',description:'',tags:'',primaryStorageId:'',primaryPath:'',backupStorageId:'',backupPath:'',backupMode:'safe',backupEnabled:true,syncOnUpload:true,scanIntervalSeconds:21600})
const tags=computed(()=>Array.from(new Set(albums.value.flatMap(a=>a.tags||[]))).sort())
const visibleAlbums=computed(()=>selectedTag.value?albums.value.filter(a=>a.tags?.some(t=>t.toLowerCase()===selectedTag.value.toLowerCase())):albums.value)
async function load(){loading.value=true;try{const [albumList,storageList]=await Promise.all([api<Album[]|null>('/albums'),api<StorageConnection[]|null>('/storage-connections')]);albums.value=albumList||[];storages.value=storageList||[]}catch(error){ElMessage.error((error as Error).message)}finally{loading.value=false}}
async function create(){try{await api('/albums',{method:'POST',body:jsonBody({...form,tags:form.tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean),backupStorageId:form.backupStorageId||'',backupPath:form.backupPath||''})});dialog.value=false;Object.assign(form,{name:'',description:'',tags:'',primaryStorageId:'',primaryPath:'',backupStorageId:'',backupPath:'',backupMode:'safe',backupEnabled:true,syncOnUpload:true,scanIntervalSeconds:21600});ElMessage.success('相册已创建，正在扫描目录');await load()}catch(error){ElMessage.error((error as Error).message)}}
function cover(album:Album){return album.coverMediaId?`/api/v1/media/${album.coverMediaId}/thumbnails/preview`:''}
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><div class="eyebrow">Library</div><h1>我的相册</h1><p class="subtitle">浏览主存储中的影像，并掌握每一份备份的状态。</p></div><el-button type="primary" size="large" :icon="Plus" @click="dialog=true">新建相册</el-button></header><div v-if="tags.length" class="toolbar"><div class="tag-filter"><button class="tag-pill" :class="{active:!selectedTag}" @click="selectedTag=''">全部</button><button v-for="tag in tags" :key="tag" class="tag-pill" :class="{active:selectedTag===tag}" @click="selectedTag=tag">{{ tag }}</button></div><el-button text :icon="Refresh" :loading="loading" @click="load">刷新</el-button></div><div v-loading="loading"><div v-if="visibleAlbums.length" class="album-grid"><router-link v-for="album in visibleAlbums" :key="album.id" :to="`/albums/${album.id}`" class="album-card"><div class="album-cover"><img v-if="cover(album)" :src="cover(album)" :alt="`${album.name}封面`"><span v-else class="cover-letter">{{ album.name.slice(0,1) }}</span></div><div class="album-body"><h3>{{ album.name }}</h3><div class="album-meta"><span>{{ album.mediaCount }} 项媒体</span><span><i class="status-dot" :class="album.scanStatus" />{{ album.scanStatus==='ready'?'已同步索引':'扫描中' }}</span></div><div v-if="album.tags?.length" class="tag-row"><span v-for="tag in album.tags" :key="tag">{{ tag }}</span></div></div></router-link></div><div v-else class="surface empty-state"><div class="empty-icon"><el-icon><Picture /></el-icon></div><h2>建立第一本相册</h2><p>先添加一个存储连接，再选择其中的目录。已有照片和视频会自动被发现，不会被移动。</p><el-button v-if="!storages.length" @click="$router.push('/storages')">先去添加存储</el-button><el-button v-else type="primary" @click="dialog=true">新建相册</el-button></div></div>
  <el-dialog v-model="dialog" title="新建相册" width="min(620px,92vw)"><el-form label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="相册名称"><el-input v-model="form.name" /></el-form-item></el-col><el-col :span="12"><el-form-item label="标签"><el-input v-model="form.tags" placeholder="旅行，家人" /></el-form-item></el-col></el-row><el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="2" /></el-form-item><el-divider content-position="left">主存储</el-divider><el-row :gutter="16"><el-col :span="12"><el-form-item label="存储连接"><el-select v-model="form.primaryStorageId" style="width:100%"><el-option v-for="item in storages" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="子路径"><el-input v-model="form.primaryPath" placeholder="family/2026" /></el-form-item></el-col></el-row><el-divider content-position="left">备份（可选）</el-divider><el-row :gutter="16"><el-col :span="12"><el-form-item label="备存储"><el-select v-model="form.backupStorageId" clearable style="width:100%"><el-option v-for="item in storages.filter(s=>s.id!==form.primaryStorageId)" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="子路径"><el-input v-model="form.backupPath" placeholder="ialbum-backup/2026" /></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item label="备份模式"><el-select v-model="form.backupMode" style="width:100%"><el-option label="安全备份（不传播删除）" value="safe" /><el-option label="镜像备份（24 小时宽限）" value="mirror" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="扫描周期"><el-select v-model="form.scanIntervalSeconds" style="width:100%"><el-option label="每小时" :value="3600" /><el-option label="每 6 小时" :value="21600" /><el-option label="每天" :value="86400" /></el-select></el-form-item></el-col></el-row><el-alert v-if="form.backupMode==='mirror'" type="warning" :closable="false" title="主存储中消失的 ialbum 管理副本会在两次确认和 24 小时宽限后从备份删除。" /></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">创建并扫描</el-button></template></el-dialog>
</section></template>
