<script setup lang="ts">
import { onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Connection, Delete, Folder, FolderOpened, Plus, Refresh, Upload } from '@element-plus/icons-vue'
import { api, jsonBody } from '../lib/api'

interface StorageItem{id:string;name:string;type:'local'|'webdav'|'baidu';config:Record<string,unknown>;status:string;statusMessage:string;lastCheckedAt?:string}
interface DeviceFlow{id:string;name:string;userCode:string;verificationURL:string;status:string;errorMessage:string;expiresAt:string;storageId?:string}
const items=ref<StorageItem[]>([]);const dialog=ref(false);const loading=ref(false);const flow=ref<DeviceFlow>();let pollTimer=0
const form=reactive({type:'local',name:'',root:'',url:'',username:'',password:'',appKey:'',secretKey:''})
async function load(){loading.value=true;try{items.value=(await api<StorageItem[]|null>('/storage-connections'))||[]}catch(error){ElMessage.error((error as Error).message)}finally{loading.value=false}}
async function create(){try{if(form.type==='baidu'){flow.value=await api<DeviceFlow>('/baidu/device-flows',{method:'POST',body:jsonBody({name:form.name,appKey:form.appKey,secretKey:form.secretKey,root:form.root})});startPolling();return};const config=form.type==='local'?{root:form.root}:{url:form.url,root:form.root};const secrets=form.type==='webdav'?{username:form.username,password:form.password}:{};await api('/storage-connections',{method:'POST',body:jsonBody({name:form.name,type:form.type,config,secrets})});ElMessage.success('存储连接已添加');closeDialog();await load()}catch(error){ElMessage.error((error as Error).message)}}
function startPolling(){window.clearInterval(pollTimer);pollTimer=window.setInterval(async()=>{if(!flow.value)return;try{flow.value=await api<DeviceFlow>(`/baidu/device-flows/${flow.value.id}`);if(flow.value.status!=='pending'){window.clearInterval(pollTimer);if(flow.value.status==='authorized'){ElMessage.success('百度网盘授权成功');closeDialog();await load()}}}catch{}},4000)}
function closeDialog(){dialog.value=false;flow.value=undefined;window.clearInterval(pollTimer);Object.assign(form,{type:'local',name:'',root:'',url:'',username:'',password:'',appKey:'',secretKey:''})}
async function test(item:StorageItem){try{await api(`/storage-connections/${item.id}/test`,{method:'POST'});ElMessage.success('连接正常')}catch(error){ElMessage.error((error as Error).message)}finally{await load()}}
async function remove(item:StorageItem){try{await ElMessageBox.confirm('只删除 ialbum 中的连接信息，不会删除远端文件。','删除存储连接',{type:'warning'});await api(`/storage-connections/${item.id}`,{method:'DELETE'});await load()}catch(error){if(error!=='cancel')ElMessage.error((error as Error).message)}}
function describe(item:StorageItem){if(item.type==='local')return String(item.config.root||'');if(item.type==='webdav')return`${item.config.url||''}/${item.config.root||''}`;return`百度网盘 ${item.config.root||'/'}`}
onMounted(load);onBeforeUnmount(()=>window.clearInterval(pollTimer))
</script>
<template><section class="page"><header class="page-heading"><div><div class="eyebrow">Storage</div><h1>存储管理</h1><p class="subtitle">连接照片所在的位置，并随时确认读写状态。</p></div><el-button type="primary" size="large" :icon="Plus" @click="dialog=true">添加存储</el-button></header><div v-loading="loading" class="storage-list"><article v-for="item in items" :key="item.id" class="surface storage-row"><div class="storage-main"><div class="storage-icon">{{item.type==='webdav'?'DAV':item.type==='baidu'?'PAN':'LOCAL'}}</div><div><h3>{{item.name}}</h3><p>{{describe(item)}}</p></div></div><div style="display:flex;align-items:center;gap:12px"><span class="muted" style="font-size:13px"><i class="status-dot" :class="item.status"/>{{item.status==='ready'?'连接正常':item.statusMessage||'尚未检测'}}</span><el-button :icon="FolderOpened" title="浏览文件" @click="$router.push(`/storages/${item.id}`)">浏览</el-button><el-button circle :icon="Refresh" title="测试连接" @click="test(item)"/><el-button circle :icon="Delete" title="删除连接" @click="remove(item)"/></div></article><div v-if="!items.length" class="surface empty-state"><div class="empty-icon"><el-icon><Folder/></el-icon></div><h2>还没有存储连接</h2><p>本地目录最适合快速开始；WebDAV 可连接 NAS，百度网盘需要自己的开放平台应用凭据。</p><el-button type="primary" @click="dialog=true">添加第一个存储</el-button></div></div>
<el-dialog v-model="dialog" title="添加存储" width="min(560px,92vw)" :before-close="closeDialog"><div v-if="flow" style="text-align:center"><img :src="`/api/v1/baidu/device-flows/${flow.id}/qr`" alt="百度授权二维码" width="220" height="220" style="border-radius:14px;border:1px solid var(--line)"><h2 style="margin:18px 0 6px">扫码授权百度网盘</h2><p class="subtitle">授权码 <strong style="color:var(--ink);letter-spacing:.12em">{{flow.userCode}}</strong></p><el-button tag="a" :href="flow.verificationURL" target="_blank">打开授权页面</el-button><p class="muted" style="margin-top:18px">状态：{{flow.status==='pending'?'等待授权':flow.status}}</p><el-alert v-if="flow.errorMessage" type="error" :title="flow.errorMessage" :closable="false"/></div><el-form v-else label-position="top"><el-form-item label="存储类型"><el-segmented v-model="form.type" :options="[{label:'本地路径',value:'local'},{label:'WebDAV',value:'webdav'},{label:'百度网盘',value:'baidu'}]"/></el-form-item><el-form-item label="显示名称"><el-input v-model="form.name" placeholder="例如：家庭 NAS"/></el-form-item><template v-if="form.type==='local'"><el-form-item label="服务器绝对路径"><el-input v-model="form.root" placeholder="/Volumes/Photos"/></el-form-item><el-alert type="info" :closable="false" title="路径位于运行 ialbum 的机器上，浏览器不会读取你的本地文件。"/></template><template v-else-if="form.type==='webdav'"><el-form-item label="WebDAV 地址"><el-input v-model="form.url" placeholder="https://nas.example.com/dav"/></el-form-item><el-form-item label="连接根路径"><el-input v-model="form.root" placeholder="Photos"/></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="用户名"><el-input v-model="form.username"/></el-form-item></el-col><el-col :span="12"><el-form-item label="密码或应用密码"><el-input v-model="form.password" type="password" show-password/></el-form-item></el-col></el-row><el-alert v-if="form.url.startsWith('http://')" type="warning" :closable="false" title="HTTP 会明文传输 WebDAV 凭据，建议使用 HTTPS。"/></template><template v-else><el-form-item label="App Key"><el-input v-model="form.appKey"/></el-form-item><el-form-item label="Secret Key"><el-input v-model="form.secretKey" type="password" show-password/></el-form-item><el-form-item label="网盘根路径"><el-input v-model="form.root" placeholder="/apps/your-app"/></el-form-item><el-alert type="warning" :closable="false" title="正式使用需要获批的百度网盘开放平台应用；ialbum 不内置公共密钥。"/></template></el-form><template #footer><el-button @click="closeDialog">取消</el-button><el-button v-if="!flow" type="primary" :icon="form.type==='baidu'?Connection:Upload" @click="create">{{form.type==='baidu'?'开始授权':'保存并测试'}}</el-button></template></el-dialog></section></template>
